Repository UMC-README/front-end, pull requests merged in 2024-08, with the labels that each got.

#65 Feat: 로그인 화면 퍼블리싱 및 API 연결&공지방 입장 퍼블리싱
  src/App.jsx
  src/api/RestApi.js
  src/api/UserApi.js
  src/api/user.js
  src/axios/axios.instance.js
  src/axios/axios.method.js
  src/components/Auth/AuthBtn.jsx
  src/components/Auth/LoginInput.jsx
  src/components/Auth/SignInInput.jsx
  src/components/CustomInput.jsx
  src/contexts/UserContext.jsx
  src/pages/Auth/NoticeRoomEntry.jsx
  src/pages/Auth/SignIn.jsx
  src/pages/Auth/SignUp.jsx
Labels: 🎉 FEAT

#67 Feat: 공지글 작성 Header 퍼블리싱
  src/assets/images/close_button.svg
  src/components/Header.jsx
  src/pages/Notice/Write/Post.jsx
Labels: 🎉 FEAT

#70 Feat: signUp 페이지 수정
  src/api/user.js
  src/components/CustomInput.jsx
  src/pages/Auth/SignIn.jsx
  src/pages/Auth/SignUp.jsx
Labels: 🎉 FEAT

#74 Feat: 공지글 작성 컴포넌트 호출 방식으로 변경
  src/App.jsx
  src/components/Notice/Write/QuestionPreview.jsx
  src/components/Notice/Write/StepButton.jsx
  src/components/Notice/Write/TwoButton.jsx
  src/components/Notice/Write/TypeCheck.jsx
  src/pages/Notice/Write/MissionType.jsx
  src/pages/Notice/Write/Post.jsx
  src/pages/Notice/Write/Preview.jsx
  src/pages/Notice/Write/QuizType.jsx
  src/pages/Notice/Write/Write.jsx
Labels: 🎉 FEAT

#75 Feat: 공지글 작성 컴포넌트 이동 시 입력값 유지
  src/components/Notice/NoticeTitle.jsx
  src/components/Notice/QuizFormatLabel.jsx
  src/components/Notice/Write/QuestionPreview.jsx
  src/pages/Notice/Write/MissionType.jsx
  src/pages/Notice/Write/Post.jsx
  src/pages/Notice/Write/Preview.jsx
  src/pages/Notice/Write/QuizType.jsx
  src/pages/Notice/Write/Write.jsx
Labels: 🎉 FEAT

#79 [style] 마이페이지 퍼블리싱
  src/App.jsx
  src/assets/svgs/camera_fill.svg
  src/assets/svgs/setting.svg
  src/components/MyPage/DefaultProfile.jsx
  src/components/MyPage/NoticeRoomProfile.jsx
  src/components/MyPage/floating-button/index.jsx
  src/components/MyPage/floating-button/style.js
  src/components/MyPage/header/index.jsx
  src/components/MyPage/header/style.js
  src/components/MyPage/image/index.jsx
  src/components/MyPage/image/style.js
  src/components/MyPage/input/index.jsx
  src/components/MyPage/input/style.js
  src/components/MyPage/profile/index.jsx
  src/components/MyPage/profile/style.js
  src/hooks/use-debounce.js
  src/index.css
  src/pages/MyPage/DefaultProfileEdit.jsx
  src/pages/MyPage/EditPassword.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/NoticeRoomProfileEdit.jsx
  src/styles/MyPage/style.js
Labels: 🎉 FEAT

#84 [feat] 마이페이지 API 연동
  src/assets/images/default_profile_3.png
  src/assets/images/default_profile_8.png
  src/components/MyPage/image/index.jsx
  src/components/MyPage/image/style.js
  src/components/MyPage/profile/index.jsx
  src/components/MyPage/profile/style.js
  src/pages/MyPage/DefaultProfileEdit.jsx
  src/pages/MyPage/EditPassword.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/NoticeRoomProfileEdit.jsx
Labels: 🎉 FEAT

#88 Feat: 공지글 작성 이전으로 돌아가도 입력값 유지
  src/components/Notice/NoticeItem.jsx
  src/components/Notice/NoticePreview.jsx
  src/components/Notice/NoticeTitle.jsx
  src/components/Notice/Write/Mission.jsx
  src/components/Notice/Write/PostInput.jsx
  src/components/Notice/Write/QuestionPreview.jsx
  src/components/Notice/Write/Quiz.jsx
  src/components/Notice/Write/StepButton.jsx
  src/components/Notice/Write/TypeCheck.jsx
  src/pages/Notice/Write/MissionType.jsx
  src/pages/Notice/Write/Post.jsx
  src/pages/Notice/Write/Preview.jsx
  src/pages/Notice/Write/QuizType.jsx
  src/pages/Notice/Write/Write.jsx
Labels: 🎉 FEAT

#93 Chore: 안쓰는 import 삭제
  src/App.jsx
  src/components/CustomModal.jsx
  src/components/CustomSearch.jsx
  src/components/Main/FixedNotice.jsx
  src/components/Main/Profile.jsx
  src/components/MemberList/AcceptanceList.jsx
  src/components/MemberList/CheckList.jsx
  src/components/MemberList/CheckListMap.jsx
  src/components/MemberList/MemberListItem.jsx
  src/components/MemberList/MemberListMap.jsx
  src/components/Notice/Write/ImgUpload.jsx
  src/components/Notice/Write/Quiz.jsx
  src/pages/Main/CreateNoticeRoomSuccess.jsx
  src/pages/Main/NoticeRoomPenaltys.jsx
  src/pages/Notice/Search.jsx
  src/pages/Notice/Write/MissionType.jsx
Labels: ⚙️ CHORE

#100 Feat: 모든 잘못된 부분들을 바로잡았다
  src/App.jsx
  src/components/CustomBtn.jsx
  src/components/Header.jsx
  src/components/Main/CreateBtn.jsx
  src/components/Main/EditRoomCustomBtn.jsx
  src/components/MemberList/AcceptanceList.jsx
  src/components/MemberList/AcceptanceListMap.jsx
  src/components/MemberList/MemberInvite.jsx
  src/components/MemberList/MemberListItem.jsx
  src/components/MemberList/MemberListMap.jsx
  src/components/MemberList/MemberProfile.jsx
  src/components/MemberList/NoticeList.jsx
  src/components/MemberList/NoticeListMap.jsx
  src/components/Notice/Confirm/AcceptanceList.jsx
  src/components/Notice/Confirm/AcceptanceListMap.jsx
  src/components/Notice/Confirm/CheckList.jsx
  src/components/Notice/Confirm/CheckListMap.jsx
  src/components/Notice/Confirm/ConfirmList.jsx
  src/components/Notice/Confirm/ConfirmStatusSwitch.jsx
  src/components/Notice/NoticePreview.jsx
  src/components/Notice/NoticeTitle.jsx
  src/pages/Auth/NoticeRoomEntry.jsx
  src/pages/Auth/SignUp.jsx
  src/pages/Main/CreateNoticeRoom.jsx
  src/pages/Main/CreateNoticeRoomSuccess.jsx
  src/pages/Main/NoticeCheckRequests.jsx
  src/pages/Main/NoticeRoomPenaltys.jsx
  src/pages/Main/Penalty.jsx
  src/pages/Main/RoomMissionRequests.jsx
  src/pages/MemberList/AcceptancePage.jsx
  src/pages/MemberList/CheckListPage.jsx
  src/pages/MemberList/Invite.jsx
  src/pages/MemberList/MemberList.jsx
  src/pages/MemberList/NoticeListPage.jsx
  src/pages/MemberList/Profile.jsx
  src/pages/Notice/Confirm/Confirm.jsx
  src/pages/Notice/Confirm/ConfirmRequestApproval.jsx
  src/pages/Notice/Confirmation.jsx
  src/pages/Notice/Details.jsx
  src/pages/Notice/Main.jsx
  src/pages/Notice/RoomEdit.jsx
Labels: 🎉 FEAT

#101 Chore: NoticeTitle 컴포넌트 폴더화
  src/components/Notice/NoticeTitle.jsx
  src/components/Notice/NoticeTitle/QuizFormatLabel.jsx
  src/components/Notice/NoticeTitle/RequestStatusLabel.jsx
  src/components/Notice/NoticeTitle/UnconfirmedPeopleItem.jsx
  src/components/Notice/NoticeTitle/UnconfirmedPeopleModal.jsx
Labels: ⚙️ CHORE

#105 공지방 메인 수정
  src/components/Header.jsx
  src/components/Notice/NoticePreview.jsx
  src/components/Notice/NoticeTitle.jsx
  src/components/Notice/NoticeTitle/UnconfirmedPeopleModal.jsx
  src/components/Notice/UnconfirmedNoticeItem.jsx
  src/pages/Notice/Main.jsx
Labels: 🔨 REFACTOR

#104 [refactor] 로그인/회원가입 UI를 수정합니다.
  src/App.jsx
  src/axios/axios.instance.js
  src/components/Auth/signup/complete-step/index.jsx
  src/components/Auth/signup/complete-step/style.js
  src/components/Auth/signup/first-step/index.jsx
  src/components/Auth/signup/fourth-step/index.jsx
  src/components/Auth/signup/index.js
  src/components/Auth/signup/second-step/index.jsx
  src/components/Auth/signup/third-step/index.jsx
  src/components/common/button/index.jsx
  src/components/common/button/style.js
  src/components/common/button/theme.js
  src/components/common/flex-box/index.jsx
  src/components/common/floating-box/index.jsx
  src/components/common/floating-box/style.js
  src/components/common/header/index.jsx
  src/components/common/header/style.js
  src/components/common/input/index.jsx
  src/components/common/input/style.js
  src/components/layout/index.jsx
  src/pages/Auth/SignIn.jsx
  src/pages/Auth/SignUp.jsx
  src/pages/MyPage/DefaultProfileEdit.jsx
  src/pages/MyPage/EditPassword.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/NoticeRoomProfileEdit.jsx
Labels: 🔨 REFACTOR

#108 Feat: 공지글 GET api 연결
  src/App.jsx
  src/api/Notice/details.js
  src/components/Notice/CommentItem.jsx
  src/components/Notice/NoticeItem.jsx
  src/components/Notice/NoticePreview.jsx
  src/components/Notice/NoticeTitle.jsx
  src/pages/Notice/Details.jsx
  src/pages/Notice/Main.jsx
Labels: 🎉 FEAT

#112 [feat] 로그아웃 기능 구현
  src/components/MyPage/profile/index.jsx
  src/components/MyPage/profile/style.js
  src/pages/MyPage/MyPage.jsx
Labels: 🎉 FEAT

#113 FIx: 공지방 메인 오류 수정
  src/assets/svgs/penalty_icon.svg
  src/components/Notice/NoticePreview.jsx
  src/components/Notice/NoticeTitle.jsx
  src/components/Notice/NoticeTitle/UnconfirmedPeopleModal.jsx
  src/pages/Notice/Main.jsx
Labels: 🐞 FIX

#120 [Fix] 플로팅 버튼 위치 수정
  src/App.jsx
  src/api/Notice/noticeSubmit.js
  src/assets/svgs/add_photo.svg
  src/assets/svgs/delete_photo.svg
  src/assets/svgs/small_camera.svg
  src/components/Header.jsx
  src/components/Notice/NoticeTitle/UnconfirmedPeopleModal.jsx
  src/pages/Notice/Check/Solve.jsx
  src/pages/Notice/Main.jsx
Labels: 🐞 FIX

#118 [feat] 카카오 로그인 구현
  src/App.jsx
  src/assets/svgs/kakao_logo.svg
  src/pages/Auth/Redirect.jsx
  src/pages/Auth/SignIn.jsx
Labels: 🎉 FEAT

#124 [Fix] 퀴즈 제출화면 버튼 disabled여부 추가
  src/pages/Notice/Check/Solve.jsx
Labels: 🐞 FIX

#111 Feat: 페널티 퍼블리싱 완료 및 api 연결
  public/mock/penaltyrooms.json
  public/mock/penaltyrooms_1.json
  src/api/Main/penalty.js
  src/components/Main/EnteredNoticeRoom.jsx
  src/components/Main/MissionRequestForm.jsx
  src/components/Main/NoticeRoom.jsx
  src/components/Main/OpendNoticeRoom.jsx
  src/components/Main/PenaltyDetails.jsx
  src/components/Main/PenaltyNoticeForm.jsx
  src/components/Main/PenaltyRoomForm.jsx
  src/components/Main/PenaltyRooms.jsx
  src/components/Main/RecentNotices.jsx
  src/components/Main/RequestDataForm.jsx
  src/components/Main/RequestDatas.jsx
  src/pages/Main/CreateNoticeRoom.jsx
  src/pages/Main/CreateNoticeRoomSuccess.jsx
  src/pages/Main/NoticeRoomPenaltys.jsx
  src/pages/Main/RoomMissionRequests.jsx
Labels: 🎉 FEAT

#131 [feat] 카카오 공유하기 기능 구현
  index.html
  src/api/Member/memberListCheck.js
  src/assets/svgs/copy_icon.svg
  src/components/MemberList/MemberInvite.jsx
  src/components/common/kakao-login/index.jsx
  src/components/common/kakao-login/style.js
  src/components/layout/index.jsx
  src/pages/Auth/SignIn.jsx
Labels: 🎉 FEAT

#135 Refactor: 공지글 상세보기 props 수정
  src/components/Notice/NoticeItem.jsx
  src/pages/Notice/Details.jsx
Labels: 🔨 REFACTOR

#137 Refactor: 공지글 상세보기 내 이미지 뷰 map 적용
  src/components/Notice/NoticeItem.jsx
Labels: 🔨 REFACTOR

#139 [Style] 공지방 입장 이미지스타일 / 카카오로그인 버튼 위치 수정
  src/components/MemberList/MemberInvite.jsx
  src/components/common/kakao-login/style.js
  src/pages/Auth/NoticeRoomEntry.jsx
  src/pages/Auth/SignIn.jsx
Labels: 🎨 STYLE

#141 공지방 메인 링크 연결
  src/api/Notice/noticeMain.js
  src/components/Notice/NoticeTitle.jsx
  src/components/Notice/UnconfirmedNoticeItem.jsx
  src/pages/Notice/Main.jsx
Labels: 🎉 FEAT

#146 Feat: 공지방 입장 로딩스피너 추가
  src/components/Notice/LoadingSpinner.jsx
  src/pages/Auth/NoticeRoomEntry.jsx
Labels: 🎉 FEAT

#148 [feat] 달력을 이용한 날짜 선택 구현 및 공지글 작성 API 연동
  package-lock.json
  package.json
  src/api/Notice/write.js
  src/assets/svgs/arrow_right.svg
  src/assets/svgs/back_button.svg
  src/components/CustomInput.jsx
  src/components/Header.jsx
  src/components/MemberList/MemberListItem.jsx
  src/components/Notice/Write/ImgUpload.jsx
  src/components/Notice/Write/PostInput.jsx
  src/components/Notice/Write/QuestionInput.jsx
  src/components/Notice/Write/first-step/index.jsx
  src/components/Notice/Write/second-step/calendar/index.jsx
  src/components/Notice/Write/second-step/calendar/style.js
  src/components/Notice/Write/second-step/index.jsx
  src/components/Notice/Write/third-step/index.jsx
  src/components/common/chip/index.jsx
  src/components/common/chip/theme.js
  src/index.css
  src/pages/MyPage/DefaultProfileEdit.jsx
  src/pages/MyPage/NoticeRoomProfileEdit.jsx
  src/pages/Notice/Details.jsx
  src/pages/Notice/Write/MissionType.jsx
  src/pages/Notice/Write/Post.jsx
  src/pages/Notice/Write/Preview.jsx
  src/pages/Notice/Write/QuizType.jsx
  src/pages/Notice/Write/Write.jsx
Labels: 🎉 FEAT

#151 [feat] 공지글 작성 시 tooltip 구현
  src/components/Notice/Write/second-step/index.jsx
  src/hooks/use-outside-click.js
Labels: 🎉 FEAT

#153 [refactor] 수정된 s3 엔드포인트 반영
  src/components/Notice/Write/ImgUpload.jsx
  src/components/Notice/Write/first-step/index.jsx
  src/components/Notice/Write/second-step/index.jsx
  src/components/Notice/Write/third-step/index.jsx
  src/pages/MyPage/DefaultProfileEdit.jsx
  src/pages/MyPage/NoticeRoomProfileEdit.jsx
  src/pages/Notice/Write/Write.jsx
Labels: 🔨 REFACTOR

#147 Feat: 댓글 삭제 API 연결
  src/api/Notice/details.js
  src/components/Notice/CommentItem.jsx
  src/pages/Notice/Details.jsx
Labels: 🎉 FEAT

#159 [fix] 로그인 버튼 키보드 따라 올라가는 현상 해결
  src/api/Auth/user.js
  src/components/Notice/Write/second-step/index.jsx
  src/components/common/kakao-login/index.jsx
  src/components/common/kakao-login/style.js
  src/pages/Auth/SignIn.jsx
Labels: 🐞 FIX

#160 [feat] 공지방 메인 패널티 팝업 구현
  src/api/Notice/noticeMain.js
  src/pages/Notice/Main.jsx
  src/redux/Notice/NoticeActions.js
  src/redux/Notice/NoticeReducer.js
Labels: 🎉 FEAT

#162 [Feat] 퀴즈/미션 제출 화면 구현
  src/App.jsx
  src/api/Notice/noticeSubmit.js
  src/assets/svgs/paperplane.svg
  src/assets/svgs/right_answer.svg
  src/assets/svgs/wrong_answer.svg
  src/pages/Notice/Check/Results.jsx
  src/pages/Notice/Check/Solve.jsx
  src/pages/Notice/Main.jsx
  src/redux/Notice/NoticeActions.js
  src/redux/Notice/NoticeReducer.js
Labels: 🎉 FEAT

#166 [Refactor] 공지방 메인 수정사항
  src/components/Notice/NoticePreview.jsx
  src/pages/Notice/Main.jsx
Labels: 🔨 REFACTOR

#172 Feat: 공지방 수정/삭제 완료 및 공지방 생성 api 연동 수정
  public/mock/createnoticeroom.json
  public/mock/createsuccess.json
  public/mock/entered.json
  public/mock/mission.json
  public/mock/missiondetail_1.json
  public/mock/missiondetail_2.json
  public/mock/opened.json
  src/api/Main/createnoticeroom.js
  src/api/Main/home.js
  src/api/Notice/roomedit.js
  src/components/CustomBtn.jsx
  src/components/Main/CreateNoticeRoomForm.jsx
  src/components/Main/OpendNoticeRoom.jsx
  src/components/Main/Profile.jsx
  src/components/Notice/RoomEditModal.jsx
  src/pages/Main/CreateNoticeRoom.jsx
  src/pages/Notice/RoomEdit.jsx
Labels: 🎉 FEAT, 🐞 FIX

#179 Feat: 공지 상세 -> 공지 확인 navigate 연결
  src/components/Notice/NoticeItem.jsx
Labels: 🎉 FEAT

#181 [Fix] 공지방 메인 사진 안나오는 오류 수정
  src/components/Notice/NoticePreview.jsx
Labels: 🐞 FIX

#175 [Feat] 확인요청내역 api연결마무리
  src/api/Member/memberListCheck.js
  src/assets/svgs/icons.jsx
  src/components/MemberList/MemberListItem.jsx
  src/components/MemberList/MemberListMap.jsx
  src/components/MemberList/MemberProfile.jsx
  src/components/Notice/Confirm/AcceptanceList.jsx
  src/components/Notice/Confirm/AcceptanceListMap.jsx
  src/components/Notice/Confirm/CheckList.jsx
  src/components/Notice/Confirm/CheckListMap.jsx
  src/components/Notice/Confirm/ConfirmList.jsx
  src/components/Notice/Confirm/ConfirmListMap.jsx
  src/components/Notice/Confirm/ConfirmStatusSwitch.jsx
  src/pages/MemberList/Profile.jsx
  src/pages/Notice/Confirm/ConfirmRequestApproval.jsx
  src/redux/CheckSlice.jsx
Labels: 🎉 FEAT

#185 [style] 메인 페이지 입장한 공지방, 개설한 공지방 grid 스타일 구현
  src/components/Main/EnteredNoticeRoom.jsx
  src/components/Main/NoticeRoom.jsx
  src/components/Main/OpendNoticeRoom.jsx
Labels: 🎨 STYLE

#186 Feat: 주소 공유 기능 추가
  src/components/Notice/NoticeTitle.jsx
Labels: 🎉 FEAT

#189 Fix: 미션제출 기타사항 charCount 위치조정
  src/pages/Notice/Check/Solve.jsx
Labels: 🔨 REFACTOR

#192 Refactor: 공지글 상세보기 Header 수정
  src/components/Header.jsx
  src/pages/Notice/Details.jsx
Labels: 🔨 REFACTOR

#187 [Feat] QA반영 기능 추가
  src/assets/svgs/icons.jsx
  src/components/MemberList/MemberInvite.jsx
  src/components/MemberList/MemberListDetails.jsx
  src/components/MemberList/MemberListItem.jsx
  src/components/MemberList/MemberListMap.jsx
  src/components/MemberList/MemberProfile.jsx
  src/components/Notice/Confirm/AcceptanceListMap.jsx
  src/components/Notice/Confirm/CheckListMap.jsx
  src/components/Notice/Confirm/ConfirmList.jsx
  src/components/Notice/Confirm/ConfirmListMap.jsx
  src/pages/Notice/Confirm/ConfirmRequestApproval.jsx
  src/redux/KeySlice.jsx
Labels: 🎉 FEAT, 🔨 REFACTOR

#198 Fix: 빈 댓글 작성 오류 수정
  src/pages/Notice/Details.jsx
Labels: 🐞 FIX

#200 Refactor: 공지글 상세보기의 더보기에 관리자 기능 추가
  src/components/Notice/NoticeItem.jsx
  src/pages/Notice/Details.jsx
Labels: 🔨 REFACTOR

#202 Refactor: 관리자는 공지글 제목에 제출 상태 안뜨게 수정
  src/components/Notice/NoticeTitle.jsx
Labels: 🔨 REFACTOR

#205 [Fix] QA반영 fix
  src/components/MemberList/MemberInvite.jsx
  src/components/MemberList/MemberListItem.jsx
  src/components/Notice/Confirm/AcceptanceList.jsx
  src/components/Notice/Confirm/AcceptanceListMap.jsx
  src/components/Notice/Confirm/CheckList.jsx
  src/components/Notice/Confirm/CheckListMap.jsx
  src/components/Notice/Confirm/ConfirmList.jsx
  src/components/Notice/Confirm/ConfirmListMap.jsx
  src/components/Notice/Confirm/ConfirmStatusSwitch.jsx
  src/pages/Notice/Confirm/Confirm.jsx
Labels: 🐞 FIX, 🔨 REFACTOR

#208 Feat: 닉네임 공백 시 에러메세지 출력
  src/pages/Auth/NoticeRoomEntry.jsx
Labels: 🎉 FEAT

#206 Feat: 공지 확인 활성화 조건 부여
  src/components/Notice/NoticeItem.jsx
  src/pages/Notice/Details.jsx
Labels: 🎉 FEAT

#209 Feat: 공지방 메인 검색기능 추가
  src/components/Header.jsx
  src/pages/Notice/Check/Solve.jsx
  src/pages/Notice/Main.jsx
Labels: 🎉 FEAT

#212 Fix: 공지방 메인, 공지글 상세 줄바꿈 안되는 오류 수정
  src/components/Notice/NoticeItem.jsx
  src/components/Notice/NoticePreview.jsx
Labels: 🐞 FIX

#213 Refactor: 입력창 반응형으로 수정
  src/components/CustomInput.jsx
Labels: 🔨 REFACTOR

#214 [FIX] QA 2차 반영
  src/api/Main/home.js
  src/components/Main/EnteredNoticeRoom.jsx
  src/components/Main/FixedNotice.jsx
  src/components/Main/OpendNoticeRoom.jsx
  src/components/Main/RecentNotices.jsx
  src/pages/Main/Home.jsx
Labels: 🐞 FIX, 🔨 REFACTOR

#218 Refactor: 헤더 홈 버튼 추가
  src/assets/svgs/homeicon.svg
  src/components/Header.jsx
  src/pages/Auth/SignUp.jsx
  src/pages/Notice/Confirm/Confirm.jsx
Labels: 🔨 REFACTOR

#224 [fix] QA 반영
  src/components/common/header/index.jsx
  src/components/common/header/style.js
  src/pages/Auth/SignUp.jsx
  src/pages/MyPage/DefaultProfileEdit.jsx
  src/pages/MyPage/EditPassword.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/NoticeRoomProfileEdit.jsx
Labels: 🐞 FIX

#226 Refactor: 추방 멤버 댓글 프로필 설정
  src/components/Notice/CommentItem.jsx
  src/components/Notice/NoticeItem.jsx
  src/index.css
Labels: 🔨 REFACTOR

#229 Fix: NoticeTitle에 roomId 전달
  src/components/Notice/NoticeItem.jsx
  src/pages/Notice/Main.jsx
Labels: 🐞 FIX

#227 [Refactor] 검색로직 수정, 이미지 크기 조정
  src/api/Member/memberListCheck.js
  src/assets/svgs/icons.jsx
  src/components/MemberList/MemberListDetails.jsx
  src/components/MemberList/MemberListItem.jsx
  src/components/MemberList/MemberListMap.jsx
  src/components/MemberList/MemberProfile.jsx
Labels: 🔨 REFACTOR

#234 Fix: 공지 확인 버튼 수정
  src/components/Notice/NoticeItem.jsx
  src/components/Notice/Write/ImgUpload.jsx
  src/components/Notice/Write/Mission.jsx
  src/components/Notice/Write/PostInput.jsx
  src/components/Notice/Write/QuestionInput.jsx
  src/components/Notice/Write/QuestionPreview.jsx
  src/components/Notice/Write/Quiz.jsx
  src/components/Notice/Write/QuizHelp.jsx
  src/components/Notice/Write/StepButton.jsx
  src/components/Notice/Write/TypeCheck.jsx
  src/pages/Notice/Write/MissionType.jsx
  src/pages/Notice/Write/Preview.jsx
  src/pages/Notice/Write/QuizType.jsx
Labels: 🐞 FIX

#238 [fix] QA 반영
  src/components/Auth/signup/complete-step/index.jsx
  src/components/Auth/signup/first-step/index.jsx
  src/components/Auth/signup/fourth-step/index.jsx
  src/components/Auth/signup/second-step/index.jsx
  src/components/Auth/signup/third-step/index.jsx
  src/pages/Auth/SignUp.jsx
Labels: 🐞 FIX

#241 Rename: 폴더 구조 및 파일 위치 정리
  src/App.jsx
  src/components/Auth/LoadingSpinner.jsx
  src/components/Auth/ProgressBar.jsx
  src/components/Notice/Detail/CommentItem.jsx
  src/components/Notice/Detail/NoticeItem.jsx
  src/components/Notice/Main/NoticePreview.jsx
  src/components/Notice/Main/UnconfirmedNotice.jsx
  src/components/Notice/Main/UnconfirmedNoticeItem.jsx
  src/pages/Auth/NoticeRoomEntry.jsx
  src/pages/Notice/Details.jsx
  src/pages/Notice/Main.jsx
Labels: ✍🏻 RENAME

#243 STYLE: CustomBtn 글자 크기, 두께 수정
  src/components/CustomBtn.jsx
Labels: 🎨 STYLE

#245 Refactor/#242
  src/components/Main/CreateNoticeRoomForm.jsx
  src/components/Main/CreateNoticeRoomSuccessForm.jsx
  src/components/MemberList/MemberInvite.jsx
  src/components/common/kakao-button/index.jsx
  src/components/common/kakao-button/style.js
  src/components/common/kakao-login/index.jsx
  src/pages/Auth/SignIn.jsx
  src/pages/Main/CreateNoticeRoomSuccess.jsx
Labels: 🔨 REFACTOR

#244 Refactor: 콘솔 지우기
  src/api/Main/noticecheckrequests.js
  src/components/Main/RequestDatas.jsx
Labels: 🔨 REFACTOR

#248 Refactor 247
  src/api/Member/memberListCheck.js
  src/components/MemberList/MemberListMap.jsx
Labels: 🔨 REFACTOR
